#SPDX-License-Identifier: MIT-0
---
# tasks file for ansible-role-wireguard

- name: Install WireGuard
  import_tasks: install-wireguard.yml

- name: Create keys
  import_tasks: create-keys.yml

- name: Read keys
  import_tasks: read-keys.yml

- name: Configure WireGuard
  import_tasks: configure-wireguard.yml
